name: update schedule
on:
  schedule:
  - cron: '10 * * * *'
  workflow_dispatch:

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: execute echo command
        run: echo "Hello World!"
